

const API_URL = 'http://psirenity.southeastasia.cloudapp.azure.com:5001/';
// This is token get from wagger or anywhere and must be token of admin.
const TOKEN_ADMIN = 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg3RjgwOURBMTlEOTFGRUU1NzczNUY4RDI4RkQ1NjFGIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NDg1NDczMDIsImV4cCI6MTY0ODYzMzcwMiwiaXNzIjoiaHR0cHM6Ly9wc2lyZW5pdHkuc291dGhlYXN0YXNpYS5jbG91ZGFwcC5henVyZS5jb20iLCJhdWQiOlsicHNpcmVuaXR5LmFwaSIsIm9hdXRoLmFwaSJdLCJjbGllbnRfaWQiOiJwc2lyZW5pdHkucG9ydGFsIiwic3ViIjoiY2I4ZjVkZTEtNjM4Ny00ZDE0LWE0MDctMjJmM2Y1MTVhMGMwIiwiYXV0aF90aW1lIjoxNjQ4MDk0OTEyLCJpZHAiOiJsb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiY2I4ZjVkZTEtNjM4Ny00ZDE0LWE0MDctMjJmM2Y1MTVhMGMwIiwiZGlzcGxheU5hbWUiOiJTdXBlciBBZG1pbiIsInJvbGUiOiJTdXBlciBBZG1pbmlzdHJhdG9yIiwidGltZXpvbmUiOiJBc2lhL1NhaWdvbiIsImp0aSI6IjM1QUI2MDgwQUQwRDIzRTQxQTc5RTNGNDNCOUM0RDkwIiwic2lkIjoiMzkxMUE0MEQ0NjA0QzM4QUY5N0UyMjQ0MUM3M0RDQjQiLCJpYXQiOjE2NDg1NDczMDIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCIsInBzaXJlbml0eS5hcGkiLCJvYXV0aC5hcGkiXSwiYW1yIjpbInB3ZCJdfQ.iokgoTAZ0qdseHnRrB6QZO4kKplngfn9v2cFjDJs534bhxP-I1VO6_awqj1CsfbptYgW_EhXJfBQ2NTK4DmHYMC3oMz_NS0UECz8Ko9x__TEHEHeU8Bura6wV2iq_AncLp0iuXN4ixDz2t5TLUhGnIwP-TW4iEYGkivYYEBsiSpW6PeeNOHkyjzsZdvRd3LWssfoMXE59XhVoC34ZO-H95LpDMpOBL_FfamkgOyQXQGjZBgUcy15_YNc1Aq0EYv6JMXpfdwlU6b3j2YZUIqFlJgfr5b5Az-emtF8JosexSifbA_NoE-mgzzNMAlpX1vPSQmNzeEQ4Jj95qbAvZOVrw';

const ICON_FOLDER = './icons';

const excelFile = './dataImport.xlsx'

const CATEGORY = {
    app: 0,
    user: 1,
    settings: 2,
    goalsChalleges: 3,
    nutritionSleep: 4
};

module.exports = {
    CATEGORY,
    ICON_FOLDER,
    API_URL,
    TOKEN_ADMIN,
    excelFile
}